server.name: gnoc-kibana
server.port: 5601
server.host: "0"
elasticsearch.url: "http://elasticsearch:9200"
elasticsearch.requestTimeout: 300000
elasticsearch.shardTimeout: 0
elasticsearch.ssl.verificationMode: none
xpack.monitoring.ui.container.elasticsearch.enabled: true
