server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: 6e72e4ffd4a7e4f5e9462d08111766b5022d42517c868ded6fcb73ddd82f2b8242f2fabd241a7e81e59e20cf4e83e5c3
    username: a7b52025632ede67916405ce4d927957
    password: c4114bd15ac9b53fb6f306719b98cfc2
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 40
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: true
  security:
    authentication:
      jwt:
        secret: changeit
        token-validity-in-seconds: 86400000
        token-validity-in-seconds-for-remember-me: 2592000000
logging:
  file: ./log/authen-service.log
  file.max-history: 10
  file.max-size: 10MB
  level:
    ROOT: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}%clr(:%-5L){magenta} %16X{traceId}:%16X{spanId} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39}:%-5L %16X{traceId}:%16X{spanId} : %m%n%wEx"
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: false
    probabilistic-sampler:
      sampling-rate: 0.01
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: full
application:
  passport:
    domainCode: GNOC_MICROSERVICE
    ### LIVE ###
    #    loginUrl: https://sso2.viettel.vn:8003/sso/login
    #    logoutUrl: https://sso2.viettel.vn:8003/sso/logout
    #    validateUrl: https://10.255.58.201:8003/sso/p3/serviceValidate
    #    vsaadminv3ServiceUrl: http://10.58.65.180:9005/vsaadminv3/VsaSsoService?wsdl
    #    service: http://10.255.58.106:9000/oauthVsa/home
    #    errorUrl: http://10.255.58.106:9000/oauthVsa/home
    #    redirectUrl: http://10.255.58.94:9000/#/authorize
    ### TEST ###
    loginUrl: https://10.240.202.152:8225/sso/login
    logoutUrl: https://10.240.202.152:8225/sso/logout
    validateUrl: https://10.240.202.152:8225/sso/p3/serviceValidate
    vsaadminv3ServiceUrl: http://10.240.202.152:9004/vsaadminv3/VsaSsoService?wsdl
    service: http://10.240.202.199:8060/oauthVsa/home
    errorUrl: http://10.240.202.199:8060/oauthVsa/home
    redirectUrl: http://10.240.202.123:8558/#/authorize
    ## LOCAL ###
    #    service: http://localhost:8060/oauthVsa/home
    #    errorUrl: http://localhost:8060/oauthVsa/home
    #    redirectUrl: http://localhost:3000/#/authorize
    logedInTimeOut: 60
